class Journal:
    @classmethod
    def Clear(cls) -> None: ...
    @classmethod
    def Search(cls, search: str) -> bool: ...
    @classmethod
    def WaitJournal(cls, search: str, timeout: int = 0) -> bool: ...