class Item:
    Durability: int
    MaxDurability: int
    Name: str
    Serial: int
    Contains: list[Item]
class Mobile: ...
class Point2D: ...
class Point3D: ...
class Rectangle: ...
class HotKeyEvent: ...
class Property: ...
class Bitmap: ...
class BuffInfo: ...